apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple
spec:
  containers:
  - name: sleeper
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
  tolerations:
  - key: "sg"
    operator: "Equal"
    value: "1"
    effect: "NoExecute"
